/* Edit invitation copy here, then run: node scripts/build.mjs */
const INVITATION = {
 links: {house:'https://maps.app.goo.gl/5g76cJrFAUqHd2PT9',barat:'https://maps.app.goo.gl/W2z7azZKRxYJJkMm8',walima:'https://maps.app.goo.gl/cmFGvbSi6RNm7CUe9'},
 contacts: [{key:'groom',number:'0334-5797201',tel:'+923345797201'},{key:'muneeb',number:'0333-5475580',tel:'+923335475580'},{key:'father',number:'0335-8090561',tel:'+923358090561'}],
 en: {
 title:'Haseeb & Nihal | 17–18 October 2026',skip:'Skip to celebrations',home:'Back to the beginning',barat:'Barat',walima:'Walima',rsvp:'RSVP',language:'اردو',languageLabel:'Read the invitation in Urdu',play:'Play music',pause:'Pause music',audioError:'Music could not play. Please try again.',
 bismillah:'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',eyebrow:'TOGETHER WITH OUR FAMILIES',first:'Haseeb',second:'Nihal',dates:'17 — 18 OCTOBER 2026',heroLine:'Two celebrations. One beautiful beginning.',explore:'Explore the celebrations',invitationLabel:'AN INVITATION',hosts:'Mr. & Mrs. Asif Javaid',invitation:'request the honour of your presence as we celebrate the wedding of our beloved son',groom:'Haseeb Hassan Asif',bride:'Nihal Farooq',with:'&',chapter1:'01 / THE WEDDING CELEBRATION',chapter2:'02 / THE RECEPTION',baratDate:'Saturday, 17 October 2026',walimaDate:'Sunday, 18 October 2026',baratCity:'ISLAMABAD → GUJRANWALA',walimaCity:'ISLAMABAD',sehra:'Sehra Bandi',sehraTime:'10:30 am',departure:'Departure',departureTime:'11:30 am',reception:'Reception',receptionTime:'6:00 pm',guests:'Guests time',guestsTime:'7:00 pm',dinner:'Dinner time',dinnerTime:'8:00 pm',gather:'GATHERING & DEPARTURE',house:'House 1253, Gali 10, Street 10, Sector I-10/2, Islamabad',punctual:'Please be on time for departure.',venue:'VENUE',baratVenue:'Rijas Marquee',baratAddress:'Ratta Chal, Main, Sialkot Bypass Road, Gujranwala',walimaVenue:'Glory Palace Marquee',walimaAddress:'Marquees Complex, Near Burki PSO Station, Express Highway, Islamabad',houseDirections:'Departure directions',venueDirections:'Venue directions',timezone:'All timings are in Pakistan Standard Time (UTC+5).',rsvpTitle:'We look forward to celebrating with you.',rsvpIntro:'For your response or any assistance, please call:',muneeb:'Abdul Muneeb Asif',father:'Asif Javaid',call:'Call',closing:'With love, the Asif family',credits:'Music credits',creditPrefix:'“Dreams Become Real” by Kevin MacLeod',creditLicense:'Licensed under Creative Commons: By Attribution 4.0',creditNote:'Original recording, unmodified.',footerDates:'17 & 18 OCTOBER 2026'
 },
 ur: {
 title:'حسیب اور نہال | ۱۷–۱۸ اکتوبر ۲۰۲۶',skip:'تقریبات کی تفصیلات',home:'ابتدا پر جائیں',barat:'بارات',walima:'ولیمہ',rsvp:'رابطہ',language:'English',languageLabel:'Read the invitation in English',play:'موسیقی چلائیں',pause:'موسیقی روکیں',audioError:'موسیقی نہیں چل سکی۔ دوبارہ کوشش کریں۔',
 bismillah:'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',eyebrow:'اپنے اہلِ خانہ کے ہمراہ',first:'حسیب',second:'نہال',dates:'۱۷ — ۱۸ اکتوبر ۲۰۲۶',heroLine:'دو تقریبات، ایک خوبصورت آغاز',explore:'تقریبات کی تفصیلات',invitationLabel:'دعوتِ شادی',hosts:'جناب آصف جاوید اور اہلیہ',invitation:'اپنے پیارے بیٹے کی شادی کی خوشیوں میں آپ کی شرکت کے خواہش مند ہیں',groom:'حسیب حسن آصف',bride:'نہال فاروق',with:'اور',chapter1:'۰۱ / تقریبِ بارات',chapter2:'۰۲ / دعوتِ ولیمہ',baratDate:'بروز ہفتہ، ۱۷ اکتوبر ۲۰۲۶',walimaDate:'بروز اتوار، ۱۸ اکتوبر ۲۰۲۶',baratCity:'اسلام آباد سے گوجرانوالہ',walimaCity:'اسلام آباد',sehra:'سہرا بندی',sehraTime:'صبح ۱۰:۳۰ بجے',departure:'روانگی',departureTime:'صبح ۱۱:۳۰ بجے',reception:'استقبالیہ',receptionTime:'شام ۶:۰۰ بجے',guests:'آمدِ مہمانان',guestsTime:'شام ۷:۰۰ بجے',dinner:'عشائیہ',dinnerTime:'رات ۸:۰۰ بجے',gather:'اجتماع اور روانگی',house:'مکان نمبر ۱۲۵۳، گلی ۱۰، اسٹریٹ ۱۰، سیکٹر آئی ٹین ٹو، اسلام آباد',punctual:'براہِ کرم روانگی کے لیے وقت کی پابندی فرمائیں۔',venue:'مقام',baratVenue:'ریجاس مارکی',baratAddress:'رتہ چل، مین سیالکوٹ بائی پاس روڈ، گوجرانوالہ',walimaVenue:'گلوری پیلس مارکی',walimaAddress:'مارکیز کمپلیکس، برکی پی ایس او اسٹیشن کے قریب، ایکسپریس ہائی وے، اسلام آباد',houseDirections:'روانگی کے مقام کا راستہ',venueDirections:'تقریب کے مقام کا راستہ',timezone:'تمام اوقات پاکستان کے معیاری وقت کے مطابق ہیں (UTC+5)۔',rsvpTitle:'آپ کی آمد ہماری خوشیوں کو دوبالا کرے گی',rsvpIntro:'شرکت کی اطلاع یا مزید معلومات کے لیے رابطہ فرمائیں:',muneeb:'عبدالمُنیب آصف',father:'آصف جاوید',call:'کال کریں',closing:'خلوص کے ساتھ، آصف فیملی',credits:'موسیقی کی تفصیلات',creditPrefix:'“Dreams Become Real” — کیون میکلوڈ',creditLicense:'کری ایٹو کامنز انتساب ۴.۰ کے تحت لائسنس یافتہ',creditNote:'اصل ریکارڈنگ، بغیر کسی تبدیلی کے۔',footerDates:'۱۷ اور ۱۸ اکتوبر ۲۰۲۶'
 }
};
