import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8')+';INVITATION');
const e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const t=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${e(data.en[key])}</${tag}>`;
const map=(key,label)=>`<a class="text-link" href="${data.links[key]}" target="_blank" rel="noopener noreferrer">${t(label)} <span aria-hidden="true">↗</span></a>`;
const time=(label,key)=>`<div class="time">${t(label,'span','class="time-label"')}${t(key,'strong')}</div>`;
const html=`<!doctype html>
<html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#081320"><title>${e(data.en.title)}</title><meta name="description" content="Join the Asif family for Haseeb and Nihal’s Barat on 17 October and Walima on 18 October 2026. Timings, directions and RSVP."><meta property="og:title" content="Haseeb & Nihal — Wedding Invitation"><meta property="og:description" content="17–18 October 2026 · Barat & Walima · Join us in celebration."><meta property="og:type" content="website"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/cormorant-400.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="assets/moonlit-garden.webp" as="image"><link rel="stylesheet" href="style.css"><script src="content.js" defer></script><script src="app.js" defer></script></head>
<body>
<a class="skip" href="#barat">${t('skip')}</a>
<header class="site-header"><a class="monogram" href="#home" aria-label="Back to the beginning" data-label="home">H<span>&</span>N</a><nav aria-label="Celebrations"><a href="#barat">${t('barat')}</a><a href="#walima">${t('walima')}</a><a href="#rsvp">${t('rsvp')}</a></nav><div class="controls"><button id="language" type="button" aria-label="Read the invitation in Urdu" hidden><span lang="ur">اردو</span></button><button id="music" type="button" aria-pressed="false" hidden><span class="music-icon" aria-hidden="true">♫</span> <span data-music-label>Play music</span></button></div></header>
<main>
<section class="hero" id="home" aria-labelledby="couple"><div class="hero-art" aria-hidden="true"></div><div class="aurora" aria-hidden="true"></div><div class="hero-copy"><p class="bismillah" lang="ar" dir="rtl">${data.en.bismillah}</p>${t('eyebrow','p','class="eyebrow"')}<h1 id="couple">${t('first')}<em aria-hidden="true">&</em>${t('second')}</h1>${t('heroLine','p','class="hero-line"')}${t('dates','p','class="eyebrow date"')}<div class="hero-links"><a href="#barat">${t('barat')} <span aria-hidden="true">↗</span></a><span aria-hidden="true">✧</span><a href="#walima">${t('walima')} <span aria-hidden="true">↗</span></a></div></div><a class="scroll-link" href="#invitation">${t('explore')}<span aria-hidden="true">↓</span></a></section>
<section class="invitation section" id="invitation"><div class="section-mark" aria-hidden="true">✧</div>${t('invitationLabel','p','class="eyebrow"')}${t('hosts','h2')}${t('invitation','p','class="invite-copy"')}<p class="full-names">${t('groom')}<span class="amp" data-i18n="with">&amp;</span>${t('bride')}</p></section>
<section class="event section" id="barat" aria-labelledby="barat-heading"><div class="event-intro">${t('chapter1','p','class="eyebrow"')}${t('barat','h2','id="barat-heading" class="event-title"')}${t('baratDate','p','class="event-date"')}${t('baratCity','p','class="eyebrow city"')}<div class="event-number" aria-hidden="true">17</div></div><div class="event-details"><div class="times">${time('sehra','sehraTime')}${time('departure','departureTime')}${time('reception','receptionTime')}</div><div class="location">${t('gather','p','class="eyebrow"')}${t('house','p','class="address house"')}${t('punctual','p','class="note"')}${map('house','houseDirections')}</div><div class="location">${t('venue','p','class="eyebrow"')}${t('baratVenue','h3')}${t('baratAddress','p','class="address"')}${map('barat','venueDirections')}</div></div></section>
<div class="interlude" aria-hidden="true"><span>H</span><i>✧</i><span>N</span></div>
<section class="event section walima" id="walima" aria-labelledby="walima-heading"><div class="event-intro">${t('chapter2','p','class="eyebrow"')}${t('walima','h2','id="walima-heading" class="event-title"')}${t('walimaDate','p','class="event-date"')}${t('walimaCity','p','class="eyebrow city"')}<div class="event-number" aria-hidden="true">18</div></div><div class="event-details"><div class="times two">${time('guests','guestsTime')}${time('dinner','dinnerTime')}</div><div class="location">${t('venue','p','class="eyebrow"')}${t('walimaVenue','h3')}${t('walimaAddress','p','class="address"')}${map('walima','venueDirections')}</div></div></section>
${t('timezone','p','class="timezone"')}
<section class="rsvp section" id="rsvp">${t('rsvp','p','class="eyebrow"')}${t('rsvpTitle','h2')}${t('rsvpIntro','p','class="rsvp-intro"')}<div class="contacts">${data.contacts.map(c=>`<a class="contact" href="tel:${c.tel}">${t(c.key,'span','class="contact-name"')}<bdi class="phone" dir="ltr">${c.number}</bdi><span class="call">${t('call')} <span aria-hidden="true">↗</span></span></a>`).join('')}</div></section>
</main>
<footer><a class="monogram" href="#home" aria-label="Back to the beginning" data-label="home">H<span>&</span>N</a>${t('closing','p')}${t('footerDates','p','class="eyebrow"')}<details><summary>${t('credits')}</summary><p>${t('creditPrefix')} (<a href="https://incompetech.com/">incompetech.com</a>).<br><a href="https://creativecommons.org/licenses/by/4.0/">${t('creditLicense')}</a>.<br>${t('creditNote')}</p></details></footer><p id="audio-status" class="sr-only" role="status"></p><audio id="soundtrack" src="assets/dreams-become-real.mp3" preload="none" loop></audio>
</body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);
console.log('Built index.html from content.js; English fallback is server-independent.');
