import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const d=vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8')+';INVITATION');
const e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const t=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${e(d.en[key])}</${tag}>`;
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>';
const map=(key,label)=>`<a class="direction-link" href="${d.links[key]}" target="_blank" rel="noopener noreferrer">${t(label)}${arrow}</a>`;
const number=(n)=>`<span class="step-number" aria-hidden="true">0${n}</span>`;
const step=(n,k,time,heading,copy,link,linkLabel,extra='')=>`<article class="event-step" data-step="${n-1}">${number(n)}<div class="step-content"><div class="step-top">${t(k,'p','class="eyebrow"')}${t(time,'p','class="event-time"')}</div>${t(heading,'h3')}${t(copy,'p','class="address"')}${extra}${map(link,linkLabel)}</div></article>`;
const quick=(event,date,rows,venue,address,link)=>`<section class="quick-event"><h3>${t(event)} <span aria-hidden="true">/</span></h3>${t(date,'p','class="quick-date"')}<dl>${rows.map(([a,b])=>`<div>${t(a,'dt')}${t(b,'dd')}</div>`).join('')}</dl>${t(venue,'h4')}${t(address,'p')}${map(link,'venueDirections')}</section>`;
const stageControls=(labels)=>`<div class="stage-controls" hidden>${labels.map((label,i)=>`<button type="button" data-stage="${i}"><span class="stage-dot" aria-hidden="true"></span><span class="stage-number">0${i+1}</span>${t(label)}</button>`).join('')}</div>`;
const contacts=d.contacts.map(c=>`<a class="contact" href="tel:${c.tel}"><span class="contact-name" data-i18n="${c.key}">${e(d.en[c.key])}</span><bdi class="phone" dir="ltr">${c.number}</bdi><span class="contact-arrow">${arrow}<span class="sr-only" data-i18n="call">Call</span></span></a>`).join('');
const html=`<!doctype html>
<html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#081320"><title>${e(d.en.title)}</title><meta name="description" content="An invitation under the stars. Celebrate Haseeb and Nihal’s Barat on 17 October and Walima on 18 October 2026."><meta property="og:title" content="Haseeb & Nihal — An invitation under the stars"><meta property="og:description" content="17–18 October 2026 · Barat & Walima · Two celebrations, one beautiful beginning."><meta property="og:type" content="website"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/cormorant-400.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="assets/moonlit-garden.webp" as="image"><link rel="stylesheet" href="style.css"><script src="content.js" defer></script><script src="app.js" defer></script></head>
<body>
<a class="skip" href="#barat">${t('skip')}</a>
<div class="world" aria-hidden="true"><div class="world-image"></div><div class="world-warmth"></div><div class="world-shade"></div><div class="world-light"></div></div>
<canvas id="stardust" aria-hidden="true"></canvas><div class="reading-progress" aria-hidden="true"><span></span></div>
<header class="site-header"><a class="monogram" href="#home" aria-label="Back to the beginning" data-label="home">H<i>&</i>N</a><nav aria-label="Explore the invitation" data-label="navigation"><a href="#barat">${t('barat')}</a><span aria-hidden="true">/</span><a href="#walima">${t('walima')}</a></nav><div class="header-actions"><button id="language" type="button" aria-label="Read the invitation in Urdu" hidden>اردو</button><button class="details-button" data-open-details hidden>${t('details')}<span aria-hidden="true">＋</span></button><a class="nojs-details" href="#rsvp">${t('rsvp')}</a></div></header>
<div class="experience-controls"><button id="sound" class="round-control" type="button" aria-label="Sound on" aria-pressed="false" hidden><span class="sound-bars" aria-hidden="true"><i></i><i></i><i></i><i></i></span><span class="control-tooltip" data-sound-label>Sound on</span></button><button id="motion" class="round-control" type="button" aria-label="Pause animation" aria-pressed="false" hidden><span data-motion-icon aria-hidden="true">Ⅱ</span><span class="control-tooltip" data-motion-label>Pause animation</span></button></div>
<main>
<section class="hero" id="home" aria-labelledby="couple"><div class="hero-frame" aria-hidden="true"></div><p class="bismillah" lang="ar" dir="rtl">${d.en.bismillah}</p><div class="hero-topline">${t('eyebrow','p','class="eyebrow"')}<span class="tiny-star" aria-hidden="true">✧</span>${t('dates','p','class="eyebrow"')}</div><div class="name-composition"><h1 id="couple"><span class="name name-one" data-i18n="first">Haseeb</span><span class="name-amp" aria-hidden="true">&</span><span class="name name-two" data-i18n="second">Nihal</span></h1><div class="orbit" aria-hidden="true"><span class="orbit-star">✦</span></div></div><div class="hero-bottom">${t('heroLine','p','class="hero-note"')}<a class="scroll-invitation" href="#invitation"><span class="scroll-line" aria-hidden="true"></span>${t('explore')}<span aria-hidden="true">↓</span></a><div class="hero-shortcuts"><a href="#barat"><span>17</span>${t('barat')}</a><a href="#walima"><span>18</span>${t('walima')}</a></div></div></section>
<section class="invitation section" id="invitation"><div class="invitation-aside"><span class="diamond" aria-hidden="true">✧</span>${t('invitationLabel','p','class="eyebrow"')}</div><div class="invitation-copy">${t('hosts','h2','class="reveal"')}${t('invitation','p','class="invitation-text reveal"')}<p class="full-names reveal">${t('groom')}<span class="amp" data-i18n="with">&amp;</span>${t('bride')}</p></div></section>
<section class="chapter barat" id="barat" aria-labelledby="barat-heading"><div class="chapter-layout"><div class="chapter-heading"><p class="eyebrow"><span class="chapter-index">01</span> ${t('chapter1')}</p>${t('barat','h2','id="barat-heading" class="chapter-title"')}${t('baratLead','p','class="chapter-lead"')}<div class="date-sculpture"><span class="date-day" aria-hidden="true">17</span><div>${t('october','span','class="eyebrow"')}${t('year','span','class="date-year"')}</div></div>${t('baratDate','p','class="event-date"')}${t('baratCity','p','class="eyebrow chapter-city"')}<div class="chapter-meter" aria-hidden="true"><span></span></div></div><div class="event-steps">${step(1,'morning','sehraTime','sehra','house','house','houseDirections')}${step(2,'road','departureTime','departure','house','house','houseDirections',t('punctual','p','class="note"'))}${step(3,'evening','receptionTime','baratVenue','baratAddress','barat','venueDirections',t('reception','p','class="note"'))}${stageControls(['sehra','departure','reception'])}</div></div></section>
<section class="between" aria-labelledby="between-title"><div class="between-sticky"><p class="eyebrow" data-i18n="nextEvening">And the next evening…</p><div class="date-transition" aria-hidden="true"><span class="transition-old">17</span><span class="transition-new">18</span></div><h2 id="between-title">${t('bridgeOne')}<em data-i18n="bridgeTwo">A new celebration.</em></h2><span class="between-star" aria-hidden="true">✧</span></div></section>
<section class="chapter walima" id="walima" aria-labelledby="walima-heading"><div class="chapter-layout"><div class="chapter-heading"><p class="eyebrow"><span class="chapter-index">02</span> ${t('chapter2')}</p>${t('walima','h2','id="walima-heading" class="chapter-title"')}${t('walimaLead','p','class="chapter-lead"')}<div class="date-sculpture"><span class="date-day" aria-hidden="true">18</span><div>${t('october','span','class="eyebrow"')}${t('year','span','class="date-year"')}</div></div>${t('walimaDate','p','class="event-date"')}${t('walimaCity','p','class="eyebrow chapter-city"')}<div class="chapter-meter" aria-hidden="true"><span></span></div></div><div class="event-steps">${step(1,'guests','guestsTime','walimaVenue','walimaAddress','walima','venueDirections')}${step(2,'evening','dinnerTime','dinner','walimaAddress','walima','venueDirections')}${stageControls(['guests','dinner'])}</div></div></section>
<section class="finale section" id="rsvp"><div class="finale-kicker"><span aria-hidden="true">✧</span>${t('rsvp','p','class="eyebrow"')}<span aria-hidden="true">✧</span></div>${t('rsvpTitle','h2','class="reveal"')}${t('rsvpIntro','p','class="rsvp-intro reveal"')}<div class="contacts">${contacts}</div><div class="celebration"><button id="celebrate" class="celebrate-button" hidden><span class="celebrate-symbol" aria-hidden="true">✦</span>${t('celebrate')}</button><p id="celebration-status" role="status" data-i18n="light">A little joy, just for you.</p></div></section>
</main>
<footer><a class="monogram" href="#home" aria-label="Back to the beginning" data-label="home">H<i>&</i>N</a>${t('closing','p','class="closing"')}${t('timezone','p','class="timezone"')}<a class="back-top" href="#home">${t('backTop')} <span aria-hidden="true">↑</span></a></footer>
<dialog id="details-dialog" aria-labelledby="details-title"><div class="dialog-top"><span class="eyebrow">17 / 18 · 2026</span><button id="close-details" aria-label="Close details" data-label="close">×</button></div>${t('allDetails','h2','id="details-title"')}${t('quickIntro','p','class="quick-intro"')}${quick('barat','baratDate',[['sehra','sehraTime'],['departure','departureTime'],['reception','receptionTime']],'baratVenue','baratAddress','barat')}<div class="quick-house">${t('gather','h4')}${t('house','p')}${t('punctual','p','class="note"')}${map('house','houseDirections')}</div>${quick('walima','walimaDate',[['guests','guestsTime'],['dinner','dinnerTime']],'walimaVenue','walimaAddress','walima')}<div class="quick-contacts">${t('rsvp','h3')}${contacts}</div>${t('timezone','p','class="timezone"')}</dialog><p id="audio-status" class="sr-only" role="status"></p>
</body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);
console.log('Built the immersive invitation with a complete static fallback.');
